GET http://localhost:8080/ufo/5
###
GET http://localhost:8080/events/40
###
POST http://localhost:8080/events/post HTTP/1.1
content-type: application/json

{
    "title": "Democracy in the Age of Big Data and AI.",
    "date": "2021-09-16",
    "start": "17:00",
    "end": "20:00",
    "city": "London",
    "country": "Great Britain",
    "location": "Lyceum Theatre",
    "adress": "21 Wellington St, London WC2E 7RQ, United Kingdom",
    "description": "Amy Webb, futurist, NYU professor, and award-winning author, has spent much of the last decade researching, discussing, and meeting with people and organizations about artificial intelligence. “We’ve reached a fever pitch in all things AI,” she says. Now it’s time to step back to see where it’s going.<br><a target='window_new' href='https://www.technologyreview.com/2019/02/26/66043/why-ai-is-a-threat-to-democracyand-what-we-can-do-to-stop-it/'>Read more</a>",
    "image": "https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80"
}
###
GET http://localhost:8080/data

###

DELETE  http://localhost:8080/events/4
