GET http://localhost:8080/ufo/5
###
GET http://localhost:8080/data
###
POST http://localhost:8080/data/6 HTTP/1.1
content-type: application/json

{
    "content": "Banana"
}
###
GET http://localhost:8080/data

###

DELETE  http://localhost:8080/events/4
